import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';
import { LoginRequest, LoginResponse } from '@mcigroupfrance/shared';

const SALT_ROUNDS = 10;

export class AuthService {
  constructor(private prisma: PrismaClient) {}

  async login(data: LoginRequest): Promise<LoginResponse | null> {
    // Find user by email
    const user = await this.prisma.user.findUnique({
      where: { email: data.email },
    });

    if (!user) {
      return null;
    }

    // Verify password
    const isPasswordValid = await bcrypt.compare(data.password, user.password);

    if (!isPasswordValid) {
      return null;
    }

    // Return user data (without password)
    return {
      token: '', // Token will be generated by the route handler
      user: {
        id: user.id,
        email: user.email,
        name: user.name,
      },
    };
  }

  async createUser(email: string, password: string, name: string) {
    const hashedPassword = await bcrypt.hash(password, SALT_ROUNDS);

    return this.prisma.user.create({
      data: {
        email,
        password: hashedPassword,
        name,
      },
    });
  }

  async getUserById(id: number) {
    return this.prisma.user.findUnique({
      where: { id },
      select: {
        id: true,
        email: true,
        name: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }
}